#index:
#    path: /
#    controller: App\Controller\DefaultController::index



# RUTAS PARA EL CONTROLADOR: USUARIO #

user:
    path: /usuario
    controller: App\Controller\UserController::index



# RUTAS PARA EL CONTROLADOR: VIDEO #

video:
    path: /video
    controller: App\Controller\VideoController::index